### ISSUE TITLE
Hardware for testing

### ISSUE THREAD

**Issue by infinity0** [RSpliet/kernel-nouveau-nv50-pm#3]
Hi, I have a GeForce GTX 560 Ti (GF114) and am highly interested in this. Would you like to borrow it for testing? I will be at FOSDEM. Also I'm happy to compile and run anything you want me to. I'm running Linux 4.3 (Debian), the same kernel that this repo appears to be based out of.

**Comment by RSpliet** [comment]
Thanks!
